# Generated by Django 3.2.5 on 2021-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('image', models.URLField()),
                ('winprice', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
